version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: local_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cloverdb
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev