spring:
  application:
    name: clover
  docker:
    compose:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/cloverdb
    username: dev
    password: dev
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        show-sql: true
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/cloverdb
    user: dev
    password: dev
    locations: classpath:database/migrations
    unknown-database-version-allowed: true
